FROM node:19-alpine
WORKDIR /app
COPY . .
RUN npm install
# Build the app
RUN npm run build
# COPY . -> ALL IN CURRENT DIR and . place in /app
COPY . .  


# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV production
EXPOSE 8080
CMD ["npm", "start"]

# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app
CMD [ "npx", "serve", "build" ]